//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int IDrequest { get; set; }
        public string NameRequest { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string email { get; set; }
    
        public virtual article article { get; set; }
        public virtual leader leader { get; set; }
    }
}
